apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kqzbwx08z-go 
  janus-idp.io/tekton: kqzbwx08z-go
  backstage.io/kubernetes-id: kqzbwx08z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kqzbwx08z-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  