apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kqzbwx08z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kqzbwx08z-go 
  name: kqzbwx08z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kqzbwx08z-go 
